### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Ryuukyu313** [arcnmx/wireplumber.rs#5]
Hi, would you mind adding a license?

The Cargo.toml does say it's MIT licensed, but without an actual LICENSE file explicitly stating the license I wouldn't feel comfortable using this library.

Thanks!

**Comment by Ryuukyu313** [comment]
@arcnmx Thanks!

In case you're interested, I started porting Helvum to wireplumbere [here](https://gitlab.freedesktop.org/ryuukyu/helvum-dev/-/tree/wireplumber), and the API is 10x more convenient to use in a GTK application than the raw C bindings.

Would also love to help with whatever is neccessary to publish this to crates.io!

**Comment by arcnmx** [comment]
Ah very neat, thanks for sharing! That finally does give me a reason to clean this up for publishing, but I have been pretty busy so any help would be appreciated. The main external blocker was a glib 0.16 release, [but that's now out of the way](https://github.com/gtk-rs/gtk-rs-core/releases) so I'll try to put together a checklist for a release soon.
